title: <p align="center"> Surya Bandari </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/surya-bandari/">LinkedIn</a> |
  <a href="https://github.com/SuryaBandari247">GitHub</a>
  
  <br>   
  Work in progress
  <br>
  </p>



theme: jekyll-theme-minimal
